l = [5, 3, 8, 1, 9, 2]
IO.inspect(Enum.sort(l))
IO.inspect(Enum.sort(l, :desc))
IO.inspect(Enum.sort_by(["bb", "a", "ccc"], &String.length/1))
IO.inspect(Enum.filter(l, &(&1 > 4)))
IO.inspect(Enum.reject(l, &(&1 > 4)))
IO.inspect(Enum.sum(l))
IO.inspect(Enum.product([1, 2, 3, 4]))
IO.inspect(Enum.max(l))
IO.inspect(Enum.min(l))
IO.inspect(Enum.min_max(l))
IO.inspect(Enum.max_by(["a", "abc", "ab"], &String.length/1))
IO.inspect(Enum.count(l))
IO.inspect(Enum.count(l, &(rem(&1, 2) == 0)))
IO.inspect(Enum.take(l, 2))
IO.inspect(Enum.drop(l, 2))
IO.inspect(Enum.take(l, -2))
IO.inspect(Enum.take_while(l, &(&1 > 2)))
IO.inspect(Enum.drop_while(l, &(&1 > 2)))
IO.inspect(Enum.chunk_every(1..10, 3))
IO.inspect(Enum.chunk_every([1, 2, 3, 4], 2, 1))
IO.inspect(Enum.chunk_every([1, 2, 3, 4, 5], 2, 2, :discard))
IO.inspect(Enum.chunk_by([1, 1, 2, 3, 3], & &1))
IO.inspect(Enum.zip([1, 2, 3], [:a, :b, :c]))
IO.inspect(Enum.unzip([{1, :a}, {2, :b}]))
IO.inspect(Enum.with_index([:a, :b]))
IO.inspect(Enum.group_by(~w(apple avocado banana cherry), &String.first/1))
IO.inspect(Enum.frequencies(~w(a b a c b a)))
IO.inspect(Enum.uniq([1, 2, 1, 3, 2]))
IO.inspect(Enum.dedup([1, 1, 2, 2, 1]))
IO.inspect(Enum.flat_map([1, 2], fn x -> [x, x * 10] end))
IO.inspect(Enum.into([a: 1, b: 2], %{}), custom_options: [sort_maps: true])
IO.inspect(Enum.join(["a", "b", "c"], ", "))
IO.inspect(Enum.map_join(1..3, "-", &(&1 * 2)))
IO.inspect(Enum.reduce(1..5, fn x, acc -> x * acc end))
IO.inspect(Enum.reduce_while(1..10, 0, fn x, acc -> if acc > 10, do: {:halt, acc}, else: {:cont, acc + x} end))
IO.inspect(Enum.find(l, &(&1 > 7)))
IO.inspect(Enum.find_index(l, &(&1 == 8)))
IO.inspect(Enum.any?(l, &(&1 > 8)))
IO.inspect(Enum.all?(l, &(&1 > 0)))
IO.inspect(Enum.member?(l, 3))
IO.inspect(Enum.at(l, 2))
IO.inspect(Enum.at(l, -1))
IO.inspect(Enum.slice(l, 1..3))
IO.inspect(Enum.split(l, 2))
IO.inspect(Enum.split_with(l, &(&1 > 4)))
IO.inspect(Enum.scan(1..5, &+/2))
IO.inspect(Enum.map_reduce([1, 2, 3], 0, fn x, acc -> {x * 2, acc + x} end))
IO.inspect(Enum.intersperse([1, 2, 3], 0))
IO.inspect(Enum.empty?([]))
IO.inspect(Enum.reverse(1..5))
IO.inspect(Enum.concat([[1, 2], [3], [4, 5]]))
IO.inspect(Enum.min_by([{:a, 3}, {:b, 1}], &elem(&1, 1)))
IO.inspect(Enum.to_list(10..1//-3))
IO.inspect(Range.size(1..10//3))
IO.inspect(Stream.map(1..3, &(&1 + 1)) |> Enum.to_list())
IO.inspect(Stream.iterate(1, &(&1 * 2)) |> Enum.take(10))
IO.inspect(Stream.cycle([1, 2, 3]) |> Enum.take(7))
IO.inspect(Stream.unfold(5, fn 0 -> nil; n -> {n, n - 1} end) |> Enum.to_list())
IO.inspect(1..1_000_000 |> Stream.filter(&(rem(&1, 7) == 0)) |> Stream.map(&(&1 * 2)) |> Enum.take(5))
IO.inspect(Stream.zip([1, 2, 3], Stream.cycle([:x, :y])) |> Enum.to_list())
IO.inspect(Stream.chunk_every(1..7, 3) |> Enum.to_list())
IO.inspect(Stream.with_index([:a, :b]) |> Enum.to_list())
IO.inspect(Keyword.get([a: 1, b: 2], :b))
IO.inspect(Keyword.put([a: 1], :b, 2))
IO.inspect(Keyword.merge([a: 1, b: 2], [b: 3, c: 4]))
IO.inspect(List.flatten([1, [2, [3, 4]], 5]))
IO.inspect(List.first([1, 2]))
IO.inspect(List.last([1, 2]))
IO.inspect(List.delete([1, 2, 1], 1))
IO.inspect(List.insert_at([1, 2, 3], 1, :x))
IO.inspect(List.duplicate(:a, 3))
IO.inspect(List.to_tuple([1, 2]))
IO.inspect(Map.merge(%{a: 1}, %{b: 2}), custom_options: [sort_maps: true])
IO.inspect(Map.update(%{a: 1}, :a, 0, &(&1 + 1)))
IO.inspect(Map.new([{:x, 1}, {:y, 2}]), custom_options: [sort_maps: true])
IO.inspect(Map.filter(%{a: 1, b: 2, c: 3}, fn {_, v} -> v > 1 end), custom_options: [sort_maps: true])
IO.inspect(MapSet.new([3, 1, 2, 1]))
IO.inspect(MapSet.member?(MapSet.new([1, 2]), 2))
IO.inspect(MapSet.union(MapSet.new([1, 2]), MapSet.new([2, 3])) |> MapSet.to_list() |> Enum.sort())
