IO.inspect(Enum.chunk_every([1, 2, 3, 4, 5], 2))
IO.inspect(Enum.chunk_every([1, 2, 3, 4, 5], 3, 2, [:pad]))
IO.inspect(Enum.chunk_by([1, 1, 2, 3, 3], & &1))
IO.inspect(Enum.chunk_while(1..10, [], fn x, acc -> if rem(x, 3) == 0, do: {:cont, Enum.reverse([x | acc]), []}, else: {:cont, [x | acc]} end, fn [] -> {:cont, []}; acc -> {:cont, Enum.reverse(acc), []} end))
IO.inspect(Enum.dedup([1, 1, 2, 1]))
IO.inspect(Enum.dedup_by([{1, :a}, {1, :b}, {2, :c}], &elem(&1, 0)))
IO.inspect(Enum.frequencies(~w(a b a c b a)))
IO.inspect(Enum.frequencies_by(~w(aa b ccc dd), &String.length/1))
IO.inspect(Enum.group_by(~w(ant bee cat ape), &String.first/1))
IO.inspect(Enum.group_by(~w(ant bee cat ape), &String.first/1, &String.upcase/1))
IO.inspect(Enum.intersperse([1, 2, 3], 0))
IO.inspect(Enum.into([a: 1], %{}))
IO.inspect(Enum.into(%{a: 1}, []))
IO.inspect(Enum.join([1, 2, 3], "-"))
IO.inspect(Enum.map_join([1, 2], ",", &(&1 * 2)))
IO.inspect(Enum.map_reduce([1, 2, 3], 0, fn x, acc -> {x * 2, acc + x} end))
IO.inspect(Enum.max_by(~w(a bbb cc), &String.length/1))
IO.inspect(Enum.min_max([3, 1, 2]))
IO.inspect(Enum.product([1, 2, 3, 4]))
IO.inspect(Enum.reduce_while(1..10, 0, fn x, acc -> if acc > 10, do: {:halt, acc}, else: {:cont, acc + x} end))
IO.inspect(Enum.reject(1..6, &(rem(&1, 2) == 0)))
IO.inspect(Enum.scan(1..4, &(&1 + &2)))
IO.inspect(Enum.shuffle([1]) |> length())
IO.inspect(Enum.sort_by([%{n: 2}, %{n: 1}], & &1.n, :desc))
IO.inspect(Enum.sort([3, 1, 2], &>=/2))
IO.inspect(Enum.split_while([1, 2, 3, 1], &(&1 < 3)))
IO.inspect(Enum.take_every(1..10, 3))
IO.inspect(Enum.take_while([1, 2, 3, 1], &(&1 < 3)))
IO.inspect(Enum.drop_while([1, 2, 3, 1], &(&1 < 3)))
IO.inspect(Enum.uniq_by([1, -1, 2], &abs/1))
IO.inspect(Enum.unzip([{1, :a}, {2, :b}]))
IO.inspect(Enum.with_index(~w(a b), 1))
IO.inspect(Enum.zip_with([1, 2], [3, 4], &(&1 + &2)))
IO.inspect(Enum.find_index([1, 2, 3], &(&1 == 2)))
IO.inspect(Enum.find_value([1, 2, 3], fn x -> x > 1 && x * 10 end))
IO.inspect(Enum.count(1..10, &(rem(&1, 3) == 0)))
IO.inspect(Enum.member?(1..10, 5))
IO.inspect(Enum.random([7]))
IO.inspect(Enum.sum([1.5, 2]))
IO.inspect(Enum.flat_map_reduce([1, 2], 0, fn x, acc -> {[x, x], acc + 1} end))
IO.inspect(Enum.split([1, 2, 3], -1))
IO.inspect(Enum.at([1, 2, 3], -1))
IO.inspect(Enum.fetch([1], 3))
IO.inspect(Enum.each([], & &1))
IO.inspect(Enum.empty?(%{}))
IO.inspect(Enum.to_list(%{a: 1}))
IO.inspect(Enum.map(%{a: 1, b: 2}, fn {k, v} -> {v, k} end) |> Enum.sort())
IO.inspect(Enum.filter(%{a: 1, b: 2}, fn {_, v} -> v > 1 end))
IO.inspect(Enum.reverse([1, 2], [3, 4]))
IO.inspect(Enum.concat([1], [2]))
IO.inspect(Enum.sort([b: 2, a: 1]))
IO.inspect(Enum.sort(["b", "B", "a"]))
IO.inspect(Enum.sort([1, :a, "s", 2.0, {1}, [1], %{}]))
IO.inspect(for x <- [1, 2, 3], into: %{}, do: {x, x * x})
IO.inspect(for x <- 1..10, rem(x, 2) == 0, reduce: 0 do acc -> acc + x end)
IO.inspect((for {k, v} <- %{a: 1, b: 2}, do: "#{k}=#{v}") |> Enum.sort())
IO.inspect(for x <- [1, 1, 2], uniq: true, do: x)
IO.inspect(for <<c <- "abc">>, into: "", do: <<c + 1>>)
IO.inspect(for x <- [1, 2], y <- [:a, :b], do: {x, y})
IO.inspect(for {:ok, v} <- [{:ok, 1}, {:error, 2}, {:ok, 3}], do: v)
IO.inspect(Stream.take_while(1..100, &(&1 < 4)) |> Enum.to_list())
IO.inspect(Stream.drop(1..5, 2) |> Enum.to_list())
IO.inspect(Stream.dedup([1, 1, 2]) |> Enum.to_list())
IO.inspect(Stream.scan(1..4, &(&1 + &2)) |> Enum.to_list())
IO.inspect(Stream.uniq([1, 2, 1]) |> Enum.to_list())
IO.inspect(Stream.reject(1..6, &(rem(&1, 2) == 0)) |> Enum.to_list())
IO.inspect(Stream.intersperse([1, 2, 3], 0) |> Enum.to_list())
IO.inspect(Stream.chunk_by([1, 1, 2], & &1) |> Enum.to_list())
IO.inspect(Stream.take(Stream.repeatedly(fn -> 1 end), 3) |> Enum.to_list())
IO.inspect(Stream.each([1, 2], fn _ -> :ok end) |> Enum.to_list())
IO.inspect(Stream.filter_map([1,2,3], &(&1 > 1), &(&1 * 2)) |> Enum.to_list())
