IO.inspect(Enum.to_list(1..100))
IO.inspect(Map.new(1..40, fn i -> {i, i * i} end))
IO.inspect(%{list: Enum.to_list(1..30), other: %{nested: Enum.map(1..20, &{&1, "val#{&1}"})}})
IO.inspect(String.duplicate("abc", 40))
IO.inspect({:a, [1, 2, 3], %{b: {1, 2}}, "str"}, label: "labeled")
IO.inspect([1, 2 | 3])
IO.inspect(:foo@bar)
IO.inspect(Foo.Bar)
IO.inspect(:+)
IO.inspect(:"foo-bar")
IO.inspect([{:"foo bar", 1}])
IO.inspect(%{"key" => :val, :atom => 1})
IO.inspect(1..10//2)
IO.inspect(10..1//-1)
IO.inspect(-0.0)
IO.inspect(1.0e20)
IO.inspect(123.0)
IO.inspect([nil, true, false])
IO.inspect(%{nil: 1, true: 2})
IO.inspect(%{1 => :a, 1.0 => :b})
IO.inspect(inspect(%{a: [1, 2]}))
IO.inspect(Enum.to_list(1..60), limit: 5)
IO.inspect(%{a: 1}, pretty: false)
IO.puts(inspect(Enum.to_list(1..30), pretty: true, width: 20))
IO.inspect(["long string number one here", "long string number two here", "long string number three"])
IO.inspect({1, 2, 3, "a fairly long string inside a tuple", :some_atom_value, [1, 2, 3], %{k: :v}})
IO.inspect(self() |> is_pid)
IO.inspect([[1, 2], [3, 4]])
IO.inspect(~c"it's")
