IO.inspect(String.split("a,b,,c", ","))
IO.inspect(String.split("a,b,,c", ",", trim: true))
IO.inspect(String.split("  hello   world  "))
IO.inspect(String.split("abc", ""))
IO.inspect(String.replace("hello world", "o", "0"))
IO.inspect(String.replace("aaa", "a", "b", global: false))
IO.inspect(String.slice("hello", 1..3))
IO.inspect(String.slice("hello", -3, 2))
IO.inspect(String.at("héllo", 1))
IO.inspect(String.length("héllo"))
IO.inspect(byte_size("héllo"))
IO.inspect(String.reverse("abc"))
IO.inspect(String.pad_leading("7", 3, "0"))
IO.inspect(String.pad_trailing("ab", 5, "."))
IO.inspect(String.starts_with?("elixir", ["eli", "x"]))
IO.inspect(String.ends_with?("elixir", "xir"))
IO.inspect(String.contains?("elixir", "lix"))
IO.inspect(String.capitalize("hELLO wORLD"))
IO.inspect(String.trim_leading("  x  "))
IO.inspect(String.trim("--x--", "-"))
IO.inspect(String.to_charlist("abc"))
IO.inspect(String.codepoints("añb"))
IO.inspect(String.graphemes("añb"))
IO.inspect(String.split_at("hello", 2))
IO.inspect(String.myers_difference("abc", "abd"))
IO.inspect(String.jaro_distance("martha", "marhta"))
IO.inspect(String.bag_distance("abc", "abd"))
IO.inspect(String.to_float("3.25"))
IO.inspect(String.valid?("abc"))
IO.inspect(String.first("abc"))
IO.inspect(String.last("abc"))
IO.inspect(String.chunk("abc12de", :valid))
IO.inspect(String.replace_prefix("foobar", "foo", ""))
IO.inspect(String.replace_suffix("foobar", "bar", "baz"))
IO.inspect(String.split("a b c", " ", parts: 2))
IO.inspect(String.downcase("ÀÉÎ"))
IO.inspect(String.upcase("straße"))
IO.inspect(Integer.to_string(255, 16))
IO.inspect(Integer.parse("12abc"))
IO.inspect(Integer.parse("ff", 16))
IO.inspect(Integer.digits(1234))
IO.inspect(Integer.undigits([1, 2, 3]))
IO.inspect(Integer.pow(2, 100))
IO.inspect(Integer.gcd(12, 18))
IO.inspect(Integer.floor_div(-7, 2))
IO.inspect(Integer.mod(-7, 2))
IO.inspect(div(-7, 2))
IO.inspect(rem(-7, 2))
IO.inspect(Float.round(3.14159, 2))
IO.inspect(Float.ceil(1.1))
IO.inspect(Float.floor(-1.1))
IO.inspect(Float.to_string(1.5))
IO.inspect(Float.parse("1.5e3xyz"))
IO.inspect(round(2.5))
IO.inspect(trunc(-2.7))
IO.inspect(abs(-3))
IO.inspect(max(1, 2.0))
IO.inspect(1 / 3)
IO.inspect(2 ** 10)
IO.inspect(2.0 ** 0.5)
IO.inspect(0.1 + 0.2)
IO.inspect(1.0e-10)
IO.inspect(123456789.123)
IO.inspect(1.0e15)
IO.inspect(1.0e16)
IO.inspect(100_000_000_000_000_000_000)
IO.inspect(-12345678901234567890 * 98765432109876543210)
IO.inspect(Bitwise.band(12, 10))
IO.inspect(Bitwise.bsl(1, 70))
IO.inspect(Tuple.to_list({1, 2}))
IO.inspect(Tuple.insert_at({1, 3}, 1, 2))
IO.inspect(Tuple.delete_at({1, 2, 3}, 0))
IO.inspect(Tuple.duplicate(:a, 2))
IO.inspect(put_elem({1, 2}, 0, :x))
IO.inspect(Atom.to_string(:hello))
IO.inspect(String.to_atom("dyn_atom"))
IO.inspect(Keyword.keys(a: 1, b: 2))
IO.inspect(Keyword.delete([a: 1, b: 2, a: 3], :a))
IO.inspect(Keyword.update([a: 1], :a, 0, &(&1 * 10)))
IO.inspect(Keyword.take([a: 1, b: 2, c: 3], [:a, :c]))
IO.inspect(Keyword.has_key?([a: 1], :a))
IO.inspect(Keyword.get_values([a: 1, a: 2], :a))
IO.inspect(Keyword.split([a: 1, b: 2], [:a]))
IO.inspect(Map.to_list(%{b: 1, a: 2}) |> Enum.sort())
IO.inspect(Map.get_and_update(%{a: 1}, :a, fn v -> {v, v + 1} end))
IO.inspect(Map.pop(%{a: 1, b: 2}, :a))
IO.inspect(Map.split(%{a: 1, b: 2, c: 3}, [:a, :c]), custom_options: [sort_maps: true])
IO.inspect(Map.reject(%{a: 1, b: 2}, fn {_, v} -> v > 1 end))
IO.inspect(Map.values(%{x: 1, y: 2}) |> Enum.sort())
IO.inspect(Map.has_key?(%{a: nil}, :a))
IO.inspect(Map.put_new(%{a: 1}, :a, 2))
IO.inspect(Map.put_new_lazy(%{}, :a, fn -> 3 end))
IO.inspect(Map.new(%{a: 1}, fn {k, v} -> {v, k} end))
IO.inspect(Map.equal?(%{a: 1}, %{a: 1}))
IO.inspect(Map.intersect(%{a: 1, b: 2}, %{b: 3, c: 4}))
IO.inspect(MapSet.difference(MapSet.new([1, 2, 3]), MapSet.new([2])) |> MapSet.to_list() |> Enum.sort())
IO.inspect(MapSet.subset?(MapSet.new([1]), MapSet.new([1, 2])))
IO.inspect(MapSet.size(MapSet.new([1, 1, 2])))
IO.inspect(MapSet.put(MapSet.new(), :a))
IO.inspect(List.zip([[1, 2], [:a, :b]]))
IO.inspect(List.foldl([1, 2, 3], 0, &(&1 + &2)))
IO.inspect(List.keyfind([a: 1, b: 2], :b, 0))
IO.inspect(List.keyreplace([a: 1], :a, 0, {:a, 9}))
IO.inspect(List.keysort([{:b, 1}, {:a, 2}], 0))
IO.inspect(List.update_at([1, 2, 3], 1, &(&1 * 10)))
IO.inspect(List.replace_at([1, 2, 3], -1, :z))
IO.inspect(List.wrap(nil))
IO.inspect(List.wrap(1))
IO.inspect(List.ascii_printable?(~c"abc"))
IO.inspect(List.starts_with?([1, 2, 3], [1, 2]))
IO.inspect(Range.new(1, 10, 3) |> Enum.to_list())
IO.inspect(Enum.slice(1..10, 2..4))
IO.inspect(1..5 |> Enum.reverse() |> Enum.take(2))
