IO.inspect(Regex.match?(~r/\d+/, "abc123"))
IO.inspect(Regex.run(~r/(\w+)@(\w+)/, "mail: bob@example now"))
IO.inspect(Regex.scan(~r/\d/, "a1b2c3"))
IO.inspect(Regex.replace(~r/\s+/, "a   b \t c", " "))
IO.inspect(String.split("a1b22c333d", ~r/\d+/))
IO.inspect(Regex.named_captures(~r/(?<year>\d{4})-(?<month>\d{2})/, "date: 2024-05"))
IO.inspect("hello world" =~ ~r/wor/)
IO.inspect("hello" =~ "ell")
IO.inspect(~r/abc/i)
IO.inspect(String.capitalize("hELLO wORLD"))
IO.inspect(String.graphemes("héllo"))
IO.inspect(String.at("hello", -1))
IO.inspect(String.first("elixir"))
IO.inspect(String.split("a-b-c", "-", parts: 2))
IO.inspect(String.split("  a  b  ", " ", trim: true))
IO.inspect(String.trim_leading("xxhixx", "x"))
IO.inspect(String.replace("hello", "l", "L", global: false))
IO.inspect(String.to_atom("dynamic_atom"))
IO.inspect(String.to_float("3.25"))
IO.inspect(Integer.parse("42abc"))
IO.inspect(Float.parse("3.14xyz"))
IO.inspect(Integer.to_string(255, 16))
IO.inspect(Integer.digits(1234))
IO.inspect(Float.round(3.14159, 2))
IO.inspect(Float.ceil(2.1))
IO.inspect(String.pad_trailing("ab", 5, "."))
IO.inspect(String.slice("elixir", 1..3))
IO.inspect(String.slice("elixir", -3..-1))
IO.inspect(String.upcase("straße"))
IO.inspect(String.downcase("ÀÉÎ"))
IO.inspect(to_string(:atom))
IO.inspect(to_string(12.5))
IO.inspect(to_string([?a, ?b]))
IO.inspect(Enum.join([1, :two, "three"], "|"))
IO.inspect(String.split_at("elixir", 3))
IO.inspect(String.replace_prefix("foobar", "foo", ""))
IO.inspect(String.valid?("abc"))
IO.inspect(String.jaro_distance("martha", "marhta"))
IO.inspect("abc" |> String.to_charlist())
IO.inspect(List.to_string([?h, "ello", ~c" ", "world"]))
IO.inspect(:erlang.binary_to_list("hi"))
IO.inspect(Atom.to_string(:hello))
IO.inspect(inspect("a\"b"))
IO.inspect(String.length("👍🏽"))
IO.inspect(String.reverse("héllo"))
