[package]
name = "tonic-rt"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "tonic_rt"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
tonic-shared = { path = "../shared" }
tokio = { version = "1", features = ["rt-multi-thread", "rt", "time", "sync", "macros"] }
corosensei = "0.3"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
parking_lot = "0.12"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
pcre2-sys = "0.2"
unicode-segmentation = "1"
unicode-normalization = "0.1"
unicode-ident = "1"
