//! The standard library, written in Elixir and compiled with every program.

pub const FILES: &[(&str, &str)] = &[
    ("kernel.ex", include_str!("../../lib/kernel.ex")),
    ("exception.ex", include_str!("../../lib/exception.ex")),
    ("ex/inspect_algebra.ex", include_str!("../../lib/ex/inspect_algebra.ex")),
    ("ex/inspect.ex", include_str!("../../lib/ex/inspect.ex")),
    ("chars.ex", include_str!("../../lib/chars.ex")),
    ("ex/enum.ex", include_str!("../../lib/ex/enum.ex")),
    ("ex/stream.ex", include_str!("../../lib/ex/stream.ex")),
    ("ex/stream_reducers.ex", include_str!("../../lib/ex/stream_reducers.ex")),
    ("ex/collectable.ex", include_str!("../../lib/ex/collectable.ex")),
    ("ex/string.ex", include_str!("../../lib/ex/string.ex")),
    ("string.ex", include_str!("../../lib/string.ex")),
    ("io.ex", include_str!("../../lib/io.ex")),
    ("ex/process.ex", include_str!("../../lib/ex/process.ex")),
    ("ex/gen_server.ex", include_str!("../../lib/ex/gen_server.ex")),
    ("ex/agent.ex", include_str!("../../lib/ex/agent.ex")),
    ("ex/agent_server.ex", include_str!("../../lib/ex/agent_server.ex")),
    ("ex/supervisor.ex", include_str!("../../lib/ex/supervisor.ex")),
    ("ex/supervisor_default.ex", include_str!("../../lib/ex/supervisor_default.ex")),
    ("ex/dynamic_supervisor.ex", include_str!("../../lib/ex/dynamic_supervisor.ex")),
    ("ex/partition_supervisor.ex", include_str!("../../lib/ex/partition_supervisor.ex")),
    ("ex/task.ex", include_str!("../../lib/ex/task.ex")),
    ("ex/task_supervised.ex", include_str!("../../lib/ex/task_supervised.ex")),
    ("ex/task_supervisor.ex", include_str!("../../lib/ex/task_supervisor.ex")),
    ("erl/supervisor.erl", include_str!("../../lib/erl/supervisor.erl")),
    ("ex/logger_translator.ex", include_str!("../../lib/ex/logger_translator.ex")),
    ("ex/logger_utils.ex", include_str!("../../lib/ex/logger_utils.ex")),
    ("ex/logger_formatter.ex", include_str!("../../lib/ex/logger_formatter.ex")),
    ("erl/gen.erl", include_str!("../../lib/erl/gen.erl")),
    ("erl/gen_server.erl", include_str!("../../lib/erl/gen_server.erl")),
    ("erl/gen_event.erl", include_str!("../../lib/erl/gen_event.erl")),
    ("erl/elixir_tokenizer.erl", include_str!("../../lib/erl/elixir_tokenizer.erl")),
    ("erl/elixir_interpolation.erl", include_str!("../../lib/erl/elixir_interpolation.erl")),
    ("string_tokenizer.ex", include_str!("../../lib/string_tokenizer.ex")),
    ("erl/elixir_errors.erl", include_str!("../../lib/erl/elixir_errors.erl")),
    ("erl/elixir.erl", include_str!("../../lib/erl/elixir.erl")),
    ("erl/elixir_quote.erl", include_str!("../../lib/erl/elixir_quote.erl")),
    ("erl/elixir_aliases.erl", include_str!("../../lib/erl/elixir_aliases.erl")),
    ("erl/erl_scan.erl", include_str!("../../lib/erl/erl_scan.erl")),
    ("erl/erl_anno.erl", include_str!("../../lib/erl/erl_anno.erl")),
    ("array.ex", include_str!("../../lib/array.ex")),
    ("record.ex", include_str!("../../lib/record.ex")),
    ("eval.ex", include_str!("../../lib/eval.ex")),
    ("config.ex", include_str!("../../lib/config.ex")),
    ("macro_host.ex", include_str!("../../lib/macro_host.ex")),
    ("erl/elixir_parser.erl", include_str!("../../lib/erl/elixir_parser.erl")),
    ("erl/proc_lib.erl", include_str!("../../lib/erl/proc_lib.erl")),
    ("erl/sys.erl", include_str!("../../lib/erl/sys.erl")),
    ("erl/io_lib.erl", include_str!("../../lib/erl/io_lib.erl")),
    ("erl/io_lib_format.erl", include_str!("../../lib/erl/io_lib_format.erl")),
    ("erl/io_lib_pretty.erl", include_str!("../../lib/erl/io_lib_pretty.erl")),
    ("erl/io_lib_fread.erl", include_str!("../../lib/erl/io_lib_fread.erl")),
    ("misc.ex", include_str!("../../lib/misc.ex")),
    ("erlang.ex", include_str!("../../lib/erlang.ex")),
    ("erlang_ds.ex", include_str!("../../lib/erlang_ds.ex")),
    ("erlang_text.ex", include_str!("../../lib/erlang_text.ex")),
    ("erlang_io.ex", include_str!("../../lib/erlang_io.ex")),
    ("ex/registry.ex", include_str!("../../lib/ex/registry.ex")),
    ("global.ex", include_str!("../../lib/global.ex")),
    ("application.ex", include_str!("../../lib/application.ex")),
    ("ex/application.ex", include_str!("../../lib/ex/application.ex")),
    ("calendar.ex", include_str!("../../lib/calendar.ex")),
    ("base.ex", include_str!("../../lib/base.ex")),
    ("ex/list.ex", include_str!("../../lib/ex/list.ex")),
    ("ex/keyword.ex", include_str!("../../lib/ex/keyword.ex")),
    ("ex/tuple.ex", include_str!("../../lib/ex/tuple.ex")),
    ("ex/atom.ex", include_str!("../../lib/ex/atom.ex")),
    ("ex/function.ex", include_str!("../../lib/ex/function.ex")),
    ("ex/map.ex", include_str!("../../lib/ex/map.ex")),
    ("ex/map_set.ex", include_str!("../../lib/ex/map_set.ex")),
    ("ex/access.ex", include_str!("../../lib/ex/access.ex")),
    ("ex/range.ex", include_str!("../../lib/ex/range.ex")),
    ("ex/integer.ex", include_str!("../../lib/ex/integer.ex")),
    ("ex/option_parser.ex", include_str!("../../lib/ex/option_parser.ex")),
    ("ex/version.ex", include_str!("../../lib/ex/version.ex")),
    ("ex/uri.ex", include_str!("../../lib/ex/uri.ex")),
    ("ex/ansi.ex", include_str!("../../lib/ex/ansi.ex")),
    ("ex/json.ex", include_str!("../../lib/ex/json.ex")),
    ("erl/elixir_json.erl", include_str!("../../lib/erl/elixir_json.erl")),
    ("macro.ex", include_str!("../../lib/macro.ex")),
    ("ex/macro.ex", include_str!("../../lib/ex/macro.ex")),
    ("ex/code_normalizer.ex", include_str!("../../lib/ex/code_normalizer.ex")),
    ("ex/code_formatter.ex", include_str!("../../lib/ex/code_formatter.ex")),
    ("ex/duration.ex", include_str!("../../lib/ex/duration.ex")),
    ("ex/code_identifier.ex", include_str!("../../lib/ex/code_identifier.ex")),
    ("re.ex", include_str!("../../lib/re.ex")),
    ("ex/regex.ex", include_str!("../../lib/ex/regex.ex")),
    ("ex/string_io.ex", include_str!("../../lib/ex/string_io.ex")),
    ("ex_unit.ex", include_str!("../../lib/ex_unit.ex")),
    ("ex/ex_unit_assertions.ex", include_str!("../../lib/ex/ex_unit_assertions.ex")),
    ("ex/ex_unit_formatter.ex", include_str!("../../lib/ex/ex_unit_formatter.ex")),
    ("ex/ex_unit_cli_formatter.ex", include_str!("../../lib/ex/ex_unit_cli_formatter.ex")),
    ("ex/ex_unit_diff.ex", include_str!("../../lib/ex/ex_unit_diff.ex")),
    ("ex/ex_unit_failures_manifest.ex", include_str!("../../lib/ex/ex_unit_failures_manifest.ex")),
    ("ex/ex_unit_on_exit_handler_supervisor.ex", include_str!("../../lib/ex/ex_unit_on_exit_handler_supervisor.ex")),
    ("ex/ex_unit_main.ex", include_str!("../../lib/ex/ex_unit_main.ex")),
    ("ex/ex_unit_runner.ex", include_str!("../../lib/ex/ex_unit_runner.ex")),
    ("ex/ex_unit_runner_stats.ex", include_str!("../../lib/ex/ex_unit_runner_stats.ex")),
    ("ex/ex_unit_event_manager.ex", include_str!("../../lib/ex/ex_unit_event_manager.ex")),
    ("ex/ex_unit_filters.ex", include_str!("../../lib/ex/ex_unit_filters.ex")),
    ("ex/ex_unit_server.ex", include_str!("../../lib/ex/ex_unit_server.ex")),
    ("ex/ex_unit_on_exit_handler.ex", include_str!("../../lib/ex/ex_unit_on_exit_handler.ex")),
    ("ex/ex_unit_capture_server.ex", include_str!("../../lib/ex/ex_unit_capture_server.ex")),
    ("ex/ex_unit_callbacks.ex", include_str!("../../lib/ex/ex_unit_callbacks.ex")),
    ("ex/ex_unit_capture_io.ex", include_str!("../../lib/ex/ex_unit_capture_io.ex")),
    ("ex/ex_unit_capture_log.ex", include_str!("../../lib/ex/ex_unit_capture_log.ex")),
    ("logger.ex", include_str!("../../lib/logger.ex")),
];

/// Erlang include files available to `-include`/`-include_lib` (by basename).
pub fn erl_include(name: &str) -> Option<String> {
    match name {
        "logger.hrl" => Some(include_str!("../../lib/erl/include/logger.hrl").to_string()),
        "elixir.hrl" => Some(include_str!("../../lib/erl/include/elixir.hrl").to_string()),
        "elixir_tokenizer.hrl" => Some(include_str!("../../lib/erl/include/elixir_tokenizer.hrl").to_string()),
        _ => None,
    }
}
