# ExUnit.Case runtime support. `test`, `describe`, `setup`, tags and the
# `__ex_unit__/0,1,2` functions are generated by the compiler (exunit.rs);
# the rest of ExUnit is imported from Elixir (lib/ex/ex_unit_*.ex).

defmodule ExUnit.Case do
  defmacro __using__(_opts) do
    quote do
      import ExUnit.Callbacks
      import ExUnit.Assertions
      import ExUnit.Case, only: [register_attribute: 2, register_attribute: 3]
    end
  end

  @type env :: module() | Macro.Env.t()

  def register_attribute(env, name, opts \\ [])
  def register_attribute(_env, _name, _opts), do: :ok
  def register_describe_attribute(env, name, opts \\ [])
  def register_describe_attribute(_env, _name, _opts), do: :ok
  def register_module_attribute(env, name, opts \\ [])
  def register_module_attribute(_env, _name, _opts), do: :ok

  @doc false
  def __after_compile__(%{module: module}, _) do
    cond do
      Process.whereis(ExUnit.Server) ->
        ExUnit.Server.add_module(module, module.__ex_unit__(:config))

      true ->
        raise "cannot use ExUnit.Case without starting the ExUnit application, " <>
                "please call ExUnit.start() or explicitly start the :ex_unit app"
    end
  end
end
